server:
  port: 9090
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, trace, info
logging:
  level:
    org:
      springframework:
        web:
          filter:
            org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG